wandb_version: 1

N:
  desc: null
  value: 50
beta_d:
  desc: null
  value: 1000
beta_z:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702576242.784861
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
