wandb_version: 1

beta_d:
  desc: null
  value: 10
beta_z:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701277217.142202
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 5
      - 23
      4: 3.8.10
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
