wandb_version: 1

N:
  desc: null
  value: 50
beta_ama_recons:
  desc: null
  value: 10000
beta_d:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700340136.927584
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 5
      - 7
      - 23
      4: 3.8.10
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 3
    - 1: loss
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: tau
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: pdiff_z1z2
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: pdiff_z0z3
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: pdiff_z0z1
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: pdiff_z0z2
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: kl_z0
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: kl_z1
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: kl_z1z2
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: kl_z0z3
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: x0y0
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: x1y1
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: x0y3
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: x1y2
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    - 1: elbo
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
