wandb_version: 1

beta_a_recons:
  desc: null
  value: 1000
beta_d:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701698795.825826
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.8.10
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
